os: linux
dist: xenial
language: python
python:
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install
  - poetry run pre-commit install
script:
  - poetry run pre-commit run --all-files
  - poetry run pytest -v
