os: linux
dist: xenial
language: python

cache:
  pip: true
  directories:
  - $HOME/.cache/pre-commit
  - .hypothesis
  - .pytest_cache

branches:
  only:
  - stable
  - develop
  - /^feature\/.+$/

matrix:
  include:
  - stage: Lint and Test
    python: 3.8
    env: NOXSESSION=lint
  - python: 3.7
    env: NOXSESSION=test-3.7
  - python: 3.8
    env: NOXSESSION=test-3.8

install:
  - pip install coverage poetry nox

script:
  - nox

after_success:
  - bash <(curl -s https://codecov.io/bash)
