os: linux
dist: xenial

branches:
  only:
  - stable
  - develop
  - /^feature\/.+$/

language: python
python:
  - "3.7.7"
  - "3.8.5"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run tox
