os: linux
dist: xenial

branches:
  only:
  - stable
  - develop
  - /^feature\/.+$/

language: python

python:
  - "3.7.7"
  - "3.8.5"

install:
  - pip install poetry tox tox-travis

script:
  - tox
