?start: expr
?expr: symbol
     | atom
     | number
     | string
     | s_expression
     | vector
     | quoted

IDENTIFIER: /(?![+-]?[0-9])[\+\-\*\/\\&<=>?!_a-zA-Z0-9]+/

symbol: IDENTIFIER

atom: ":" IDENTIFIER

?number: integral | floating | fraction
integral: /-?(0|[1-9][0-9]*)/
floating: /-?(0|[1-9]+)\.[0-9]+/
fraction: /-?(0|[0-9]+)\/(0|[0-9]+)/

!string: "\"\"" | "\"" /(\\.|[^"])+/ "\""

s_expression: "(" expr* ")"
vector: "[" expr* "]"

quoted: "'" expr

%import common.WS
%ignore WS
